server:
  port: 9111
  
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.local.study.excel
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL


